### ISSUE TITLE
Gnome 43 

### ISSUE THREAD

**Issue by ggqc007** [maoschanz/sound-percentage-gs-extension#12]
Hi,

I see that the metadata file states support for gnome 43, but its not on the official page yet.

With gnome 43 officially out, any plan to resubmit on extensions.gnome.org?

Thank you much !

**Comment by peter-lyons-kehl** [comment]
Hi Romaine,

Thank you for Sound Percentage. So good.

Unfortunately, it stopped working with the most recent Manjaro (Arch Linux-derivative) update. That has GNOME 43.1 on X11:
![image](https://user-images.githubusercontent.com/4270240/202316097-901bd1a5-e950-4855-98cc-3e51a4620842.png)


The error: `Main.panel.statusArea.aggregateMenu is undefined`
![image](https://user-images.githubusercontent.com/4270240/202316290-d8342735-1163-4e4d-a885-9b61082aab14.png)


Please investigate. Thank you in advance.
