### ISSUE TITLE
Gnome 40 Support?

### ISSUE THREAD

**Issue by dimisc** [maoschanz/sound-percentage-gs-extension#5]
Please consider updating the extension for Gnome 40 support. Thanks!

**Comment by maoschanz** [comment]
i'll use gnome 40 when it'll get vertical workspaces by default

**Comment by onlyreportingissues** [comment]
Works perfectly fine with GNOME 42.

For anyone not wanting to edit anything:
You can just run this command & will be able then to install outdated extensions:

gsettings set org.gnome.shell disable-extension-version-validation "true"

( You can disable the command again by running: gsettings set org.gnome.shell disable-extension-version-validation "false" )
